# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rc174kSN2mU_Sv7T9j1Jf91-faeJG0S7

1. What are the two values of the Boolean data type? How do you write them? 
= The two values of the Boolean data type are "true" and "false"
  In programming languages, true is often represented by the integer value 1,  and false by the integer value 0.

 2. What are the three different types of Boolean operators?
= 1) AND operator
  2) OR operator
  3) NOT operator

  3. Make a list of each Boolean operator&#39;s truth tables (i.e. every possible combination of Boolean
values for the operator and what it evaluate ).
= AND operator:
Operand 1 	Operand 2  	Result
true       	true	       true
true      	false      	false
false     	true	      false
false	      false      	false
=OR operator:
Operand 1	   Operand 2 	Result
true	       true	      true
true       	false	      true
false     	true      	true
false	      false	      false

4. What are the values of the following expressions?
(5 &gt; 4) and (3 == 5)
not (5 &gt; 4)
(5 &gt; 4) or (3 == 5)
not ((5 &gt; 4) or (3 == 5))
(True and True) and (True == False)
(not False) or (not True)

= (5 > 4) and (3 == 5)

(True) and (False)
Result: False
not (5 > 4)

not (True)
Result: False
(5 > 4) or (3 == 5)

(True) or (False)
Result: True
not ((5 > 4) or (3 == 5))

not (True or False)
not (True)
Result: False
(True and True) and (True == False)

(True) and (False)
Result: False
(not False) or (not True)

(True) or (False)
Result: True

5. What are the six comparison operators?
= Equal to (==)
  Not equal to (!=)
  Greater than (>)
  Less than (<)
  Greater than or equal to (>=)
  Less than or equal to (<=)

6. How do you tell the difference between the equal to and assignment operators?Describe a
condition and when you would use one.

=  The equal to operator (==) is a comparison operator used to check if two    values or expressions are equal. The assignment operator (=), on the other hand, is used to assign a value to a variable
    
    x = 5 
    y = 10 
if x == y:
    print("x and y are equal")
else:
    print("x and y are not equal")

8. Write code that prints Hello if 1 is stored in spam, prints Howdy if 2 is stored in spam, and prints
Greetings! if anything else is stored in spam.
=  if spam == 1:
    print("Hello")
   elif spam == 2:
    print("Howdy")
   else:
    print("Greetings!")

9. If your programme is stuck in an endless loop, what keys you’ll press?
=  "Ctrl" + "C" keys

10. How can you tell the difference between break and continue?
= the main difference between them is how they affect the loop execution.
"break is used to terminate the loop immediately, while continue is used to skip the current iteration of the loop and move on to the next iteration"

11. Write a short program that prints the numbers 1 to 10 using a for loop. Then write an equivalent
program that prints the numbers 1 to 10 using a while loop.

=  for i in range(1, 11):
    print(i)
"""



